#ifndef CODE_INCLUDE_L1_DOMAIN_ERRORCODE_COMMONERROR_H_
#define CODE_INCLUDE_L1_DOMAIN_ERRORCODE_COMMONERROR_H_


#include "l0-infra/base/Status.h"

DEF_COMMON_ERROR(E_COMM_FLOW_TIMEOUT, 0x0001);


#endif /* CODE_INCLUDE_L1_DOMAIN_ERRORCODE_COMMONERROR_H_ */
